name: orion
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - arrow-cpp=4.0.1=py38hced866c_3
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h27cfd23_11
  - bottleneck=1.3.2=py38heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - decorator=5.0.6=pyhd3eb1b0_0
  - double-conversion=3.1.5=he6710b0_1
  - expat=2.3.0=h2531618_2
  - gflags=2.2.2=he6710b0_0
  - git=2.23.0=pl526hacde149_0
  - glog=0.5.0=h2531618_0
  - grpc-cpp=1.26.0=hf8bcb03_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.22.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - krb5=1.18.2=h173b8e3_0
  - libboost=1.73.0=h3ff78a5_11
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20210216=h27cfd23_1
  - libevent=2.1.8=h1ba5d50_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libthrift=0.13.0=hfb8234f_6
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.2=he6710b0_1
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy-base=1.20.3=py38h74d4b33_0
  - openssl=1.1.1k=h27cfd23_0
  - orc=1.6.7=h973521d_2
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py38h06a4308_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - python=3.8.0=h0371630_2
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py38h2531618_1
  - re2=2020.11.01=h2531618_1
  - readline=7.0=h7b6447c_5
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=pyhd3eb1b0_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - uriparser=0.9.3=he6710b0_1
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.12.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - autopep8==1.5.6
    - bleach==3.3.0
    - blis==0.7.4
    - cachetools==4.2.1
    - catalogue==2.0.3
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - cupy-cuda110==8.6.0
    - cymem==2.0.5
    - datasets==1.11.0
    - defusedxml==0.7.1
    - dill==0.3.3
    - entrypoints==0.3
    - fastrlock==0.6
    - filelock==3.0.12
    - flake8==3.9.1
    - fsspec==2021.7.0
    - git-python==1.0.3
    - gitdb==4.0.7
    - gitpython==3.1.17
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.37.0
    - huggingface-hub==0.0.12
    - idna==2.10
    - ipywidgets==7.6.3
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonlines==2.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - lightseq==1.2.0
    - markdown==3.3.4
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - multiprocess==0.70.11.1
    - murmurhash==1.0.5
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - ngram==3.3.2
    - nltk==3.6.2
    - notebook==6.3.0
    - numpy==1.20.2
    - oauthlib==3.1.0
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - pathy==0.4.0
    - pillow==8.2.0
    - portalocker==2.0.0
    - preshed==3.0.5
    - prometheus-client==0.10.1
    - protobuf==3.15.8
    - psutil==5.8.0
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pycparser==2.20
    - pydantic==1.7.3
    - pyflakes==2.3.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pyyaml==5.4.1
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rouge-score==0.0.4
    - rsa==4.7.2
    - sacrebleu==1.5.1
    - sacremoses==0.0.44
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - send2trash==1.5.0
    - seqeval==1.2.2
    - sklearn==0.0
    - smart-open==3.0.0
    - smmap==4.0.0
    - spacy==3.0.5
    - spacy-legacy==3.0.2
    - srsly==2.4.1
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.2
    - terminado==0.9.4
    - testpath==0.4.4
    - thinc==8.0.2
    - threadpoolctl==2.1.0
    - tokenizers==0.10.2
    - toml==0.10.2
    - torch==1.8.1
    - torch-tb-profiler==0.1.0
    - torchaudio==0.8.1
    - torchvision==0.9.1
    - tqdm==4.49.0
    - transformers==4.9.1
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wasabi==0.8.2
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - xxhash==2.0.2
prefix: /home/chenxingran/anaconda3/envs/ori
